import './globals.css'
import { Itim } from 'next/font/google'

const itim = Itim({ weight: '400', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }) => {
  return (
    <html lang='en'>
      <body className={itim.className}>{children}</body>
    </html>
  )
}

export default RootLayout
